### ISSUE TITLE
How to increase the font size on Windows

### ISSUE THREAD

**Issue by aks2161989** [RamonUnch/GreenPad#151]
The editor is really neat, but the font is really tiny on Windows 10. How can the font size be increased?

**Comment by RamonUnch** [comment]
you can open the layout files (`.lay` files in the types directory) and use the sz=XX to specify the font size.

More details:
```
    In the types/ dir, you'll see some .lay files. Please edit them manually.
      =========================================================
      ct=Color of Text (RGB)
      ck=Color of Keyword
      cb=Color of BackGround
      cc=Color of ControlCharactor
      cn=Color of commeNt
      cl=Color of Line no.
      ft=FonT name
      fw=Font wheight from 1 to 1000 (400=normal, 700=bold...)
      fx=Font width in points (0 means default width)
      ff=Font Flags (1:Italic/2:Underline/4:Strikeout)
      sz=font SiZe (font height in points)
      tb=TaB width
      sc=11000  (Show special chars 0|1 for: [EOF],\n,\t,space,fw-space)
      wp=WraP type (-1: no wrap 0: right edge 1: ww chars )
      ww=Wrap Width
      ws=Wrap Smart (1: wrap at word boundaries, 0: character)
      ln=show LineNo.
      =========================================================
```

By default you have `default.lay`, `html.lay`, `program.lay` and `unitext.lay`

Also some font are not scalable, so if the font is `ft=FixedSys` for example then you will be unable to resize.
You might want something as ft=Courier New

**Comment by aks2161989** [comment]
> you can open the layout files (`.lay` files in the types directory) and use the sz=XX to specify the font size.
> 
> More details:
> 
> ```
>     In the types/ dir, you'll see some .lay files. Please edit them manually.
>       =========================================================
>       ct=Color of Text (RGB)
>       ck=Color of Keyword
>       cb=Color of BackGround
>       cc=Color of ControlCharactor
>       cn=Color of commeNt
>       cl=Color of Line no.
>       ft=FonT name
>       fw=Font wheight from 1 to 1000 (400=normal, 700=bold...)
>       fx=Font width in points (0 means default width)
>       ff=Font Flags (1:Italic/2:Underline/4:Strikeout)
>       sz=font SiZe (font height in points)
>       tb=TaB width
>       sc=11000  (Show special chars 0|1 for: [EOF],\n,\t,space,fw-space)
>       wp=WraP type (-1: no wrap 0: right edge 1: ww chars )
>       ww=Wrap Width
>       ws=Wrap Smart (1: wrap at word boundaries, 0: character)
>       ln=show LineNo.
>       =========================================================
> ```
> 
> By default you have `default.lay`, `html.lay`, `program.lay` and `unitext.lay`
> 
> Also some font are not scalable, so if the font is `ft=FixedSys` for example then you will be unable to resize. You might want something as ft=Courier New

Thank you for the detailed instructions. That worked
