### ISSUE TITLE
GreenPad crash when opening check.t in Win95 OSR2

### ISSUE THREAD

**Issue by roytam1** [RamonUnch/GreenPad#178]
Test file: https://github.com/MirBSD/mksh/raw/master/check.t
and it hangs in my build.

tested with latest release(1.20):
![image](https://github.com/RamonUnch/GreenPad/assets/1192577/7c7265d3-ad0c-4781-a10f-f71bb8a1c615)
![image](https://github.com/RamonUnch/GreenPad/assets/1192577/8bbd61d0-5b1e-48c0-a957-ab2aaf091c3e)

**Comment by RamonUnch** [comment]
Strange.
I was able to reproduce on Windows 95 OSR2.5 and also when using a slightly older build, did not test the original though.
I will install VC++6 on Windows 95 when I get time, and see if I can find the crash in the debugger. Probably we are giving improper parameters to some GDI functions in some cases.
When I try to Load the file as Latin1 it does not crash, only when using UTF-8 or UTF-5 does it crashes.

**Comment by RamonUnch** [comment]
If I force the use of TextOutA over TextOutW I no longer get the crash. So maybe it is GDI that really does not like some Unicode sequences, or maybe something else is wrong.

**Comment by RamonUnch** [comment]
`GetCharWidthW()` actually crashes if you ask the width of U+FFFF.

**Comment by roytam1** [comment]
> `GetCharWidthW()` actually crashes if you ask the width of U+FFFF.

so I fixed my side with different approach: https://github.com/roytam1/rtoss/commit/fe3fa17fa2020498280346c92c4effa94e9d8452
