### ISSUE TITLE
Simplified Chinese translation

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/GreenPad#182]
Thank you for reply.
I translated greepad into `simplified Chinese` and modified the exe file directly using ResouceHack. 
Can you add `ID 2052 RC resource` to use this translation later?
Besides, what exactly is the `menu-Reconversion` function? I never understood it.

[GPad64.zip](https://github.com/RamonUnch/GreenPad/files/14155455/GPad64.zip)

![图片](https://github.com/RamonUnch/GreenPad/assets/121145522/8e14bf02-1d07-4101-a4f6-35371bc55f80)
![图片](https://github.com/RamonUnch/GreenPad/assets/121145522/d385a031-60a3-472b-b173-e04bebc7f00a)

_Originally posted by @popthezid in https://github.com/RamonUnch/GreenPad/issues/181#issuecomment-1925573872_

**Comment by RamonUnch** [comment]
I will do that as well.
The reconvert option will re-run the selection into the IME, it can be useful if you think you were blindly typing into the IME and then realize that you actually were typing just ASCII. in this case , just select the ASCII and hit the Reconvert option.

**Comment by popthezid** [comment]
> I will do that as well. The reconvert option will re-run the selection into the IME, it can be useful if you think you were blindly typing into the IME and then realize that you actually were typing just ASCII. in this case , just select the ASCII and hit the Reconvert option.

Thank you for the answer. I have a general understanding of the meaning of this function. 
So I have made some fix to the translation, please refer to the exe resources in this attachment. 
Thanks again.
[GPad64_chs.zip](https://github.com/RamonUnch/GreenPad/files/14156224/GPad64_chs.zip)

**Comment by RamonUnch** [comment]
I converted back your resource file into a workable `.rc` file, if you have more modifications to do, do it directly on the `zh_cn.rc` file.
This build should contain the Chinese translation you made, in addition to the original English and the Japanese versions.
[GPad64.zip](https://github.com/RamonUnch/GreenPad/files/14232067/GPad64.zip)
