### ISSUE TITLE
Determine version numbers for old chicago builds

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/GreenPad#64]
In Chicago 58s we do not have GetVersionEx() and GetVersion() returns: 4.00.16384
In Chicago 116 we do have GetVersionEx() and it returns 4.00.0, also GetVersion() returns: 4.00.16384

So step one is to mask the build number of GetVersion() with `~0xC000` instead of `~0x8000`.
Step two is to determine from which exact build GetVersionEx() was introduced and update the build number with this value if needed.

**Comment by RamonUnch** [comment]
```
Chicago 058s -> 4.00.0 GetVersion();
Chicago 073f -> 4.00.0 GetVersion();
Chicago 090c -> 4.00.0 GetVersion();
Chicago 099  -> 4.00.0 GetVersionEx();
Chicago 116  -> 4.00.0 GetVersionEx();
```
So we can pretend that if we have GetVersionEx() then we have at least build 99!

**Comment by roytam1** [comment]
> GetVersion() returns: 4.00.16384

from GetVersion() API documentation: (MS removed documentations about old OSes so using a backup here)
http://winapi.freetechsecrets.com/win32/WIN32GetVersion.htm

> For Windows NT and Win32s, the remaining bits in the high order word specify the build number.
> For Windows 95 the remaining bits of the high order word are reserved.

so don't do it incorrectly.

**Comment by RamonUnch** [comment]
Thanks for the info, I was mislead by Win32s testing.
I should have seen it as I have old MSDN doc form 1998...
