### ISSUE TITLE
Handle OLE Drag and Drop

### ISSUE THREAD

**Issue by roytam1** [RamonUnch/GreenPad#70]
It will be nice if we can drop URL from chrome to GreenPad.

**Comment by RamonUnch** [comment]
Sure would be nice to be a drop target for this.

**Comment by roytam1** [comment]
and if you want to do, the Top-Left system icon can be OLE drop source as well. (EmEditor and XP explorer have this implemented)

**Comment by RamonUnch** [comment]
WIP PR: #71

**Comment by roytam1** [comment]
> Similar story would apply with the `IDropSource` for both a selection (like the RichEdit control) and for the system icon.

for system icon, we may need to test if file has filename(i.e. not being a drag source for untitled) and test if it is really dragging (not using DragDetect since it will steal window messages), some code snippets can be found in wine: https://github.com/wine-mirror/wine/commit/9b057494d082094162ac796cbc7f059d9b21e9ec

**Comment by RamonUnch** [comment]
I am not a huge fan of modifying the system icon, I am used to the real system menu that drops down on click down, allowing to directly drag and release the option you want. It is an interesting exercise however.

**Comment by RamonUnch** [comment]
However with the right click It would not actually matter and would be a pure improvement for me.

**Comment by roytam1** [comment]
> I am used to the real system menu that drops down on click down

if it is implemented correctly, it should work like IE6: single-clicking and double-clicking system icon(i.e. top-left icon) should act like normal window(i.e. providing system menu for single-click, or close window when being double-clicked). only left or right button pressed down and dragging system icon providing a drop source.

**Comment by roytam1** [comment]
> However with the right click It would not actually matter and would be a pure improvement for me.

you mean providing shell menu when right-clicking system icon like XP explorer? it could be nice to have, but it will need extra care for NT3/32s/chicago.

**Comment by RamonUnch** [comment]
> if it is implemented correctly, it should work like IE6: single-clicking and double-clicking system icon(i.e. top-left icon) should act like normal window(i.e. providing system menu for single-click, or close window when being double-clicked). only left or right button pressed down and dragging system icon providing a drop source.

Yes indeed, but I do not like much IE6 style system menu, I will make it optional because it will interesting anyway.
I am working right now on a drop source handler, it takes a ton of unction just to make a IDataObject...

**Comment by roytam1** [comment]
> it takes a ton of unction just to make a IDataObject

ah, yeah that happens. especially if you don't want to use shell32 functions.

**Comment by RamonUnch** [comment]
I was traveling around this week and I was mostly offline, The drop source is ready and should be Win32s compatible.
I still need to fix the issue that when dragging text over itself, it should do nothing instead of deleting it.
