### ISSUE TITLE
Help -> About menu

### ISSUE THREAD

**Issue by DotNetTester** [RamonUnch/GreenPad#73]
A minor suggestion. A help menu with an About submenu at the end of the main menu with a dialog that displays the version of GreenPad installed.

I'm used to seeing this in Notepad and it's noticeable that it's missing in GreenPad.

**Comment by RamonUnch** [comment]
it does miss in green pad for sure.

**Comment by RamonUnch** [comment]
[GreenPad1.17beta.zip](https://github.com/RamonUnch/GreenPad/files/10834592/GreenPad1.17beta.zip)
![Abouteg](https://user-images.githubusercontent.com/74856804/221433564-26c1fa2d-044b-4be7-9e42-a96d9f78b50f.png)

As usual you get a bunnch of versions, unless you are using really old systems, (NT3.1 Win32s or Chicago) anything newer that NT3.50 and Win95 should run `GreenPad.exe` also you got 64 bit version as well.

I am planning on making an actual release sometime soon.

**Comment by DotNetTester** [comment]
It's typically a dialog and not a message box.  I recommend larger text with more spacing and many about dialogs have the program icon on the upper or middle left, the left of the text.

**Comment by roytam1** [comment]
> It's typically a dialog and not a message box. I recommend larger text with more spacing and many about dialogs have the program icon on the upper or middle left, the left of the text.

so you want a `ShellAbout()` dialog:
![image](https://user-images.githubusercontent.com/1192577/221489730-7640651e-0f97-499b-a9d4-1f3a239ac012.png)

**Comment by RamonUnch** [comment]
Sure bit I do not know how to get rid of the Microsoft prefix.
GreenPad is not made by MS...

The only thing you can change is title text + program name after Microsoft and two extra lines of info.

**Comment by RamonUnch** [comment]
The best I can do is:

![image](https://user-images.githubusercontent.com/74856804/221500624-5badf19e-bdae-49ba-b397-71db1dfbb3b1.png)

**Comment by roytam1** [comment]
for reference, a MFC application about dialog:
![image](https://user-images.githubusercontent.com/1192577/221523267-e4e81f65-4175-4b16-a4a4-d94e24a1743a.png)

**Comment by RamonUnch** [comment]
WIP
![image](https://user-images.githubusercontent.com/74856804/221529058-3a6f35cc-fe4c-4344-bdc8-7a2ec818960f.png)

**Comment by roytam1** [comment]
maybe you can add a Ctrl-C handler to copy first 3 lines for diagnostics/bug reporting?

**Comment by RamonUnch** [comment]
Even simpler, I made relevant parts to be Edit dialogs

![image](https://user-images.githubusercontent.com/74856804/221542082-5db88d01-0517-4700-91ff-c7677a4ef915.png)

**Comment by DotNetTester** [comment]
> WIP ![image](https://user-images.githubusercontent.com/74856804/221529058-3a6f35cc-fe4c-4344-bdc8-7a2ec818960f.png)

That's very close to what I was thinking about except with the text a little larger. The text would be easier for some people to read and look slightly nicer if it was bigger. It's true that it would be good for troubleshooting to be able copy the text as well. A read only edit box, basically.

**Comment by DotNetTester** [comment]
The built in ShellAbout API is too clunky with extra junk that isn't needed for most about boxes. I personally wouldn't use it.

**Comment by RamonUnch** [comment]
The dialog uses the default dialog font, I can of course increase the font size but keep in mind that the dpi of y monitor is set to 96, most people now use 120 or more  meaning the font will look much larger.
If the DPI setting on your screen is so small that the common dialogs appear to small to your eyes you might also consider increasing the DPI value. I can push up a little the font size but not by much before it looks out of place.

here the size is set to 10 points.
[GreenPad-1.17bin_beta2.zip](https://github.com/RamonUnch/GreenPad/files/10843331/GreenPad-1.17bin_beta2.zip)

**Comment by roytam1** [comment]
> Even simpler, I made relevant parts to be Edit dialogs
> 
> ![image](https://user-images.githubusercontent.com/74856804/221542082-5db88d01-0517-4700-91ff-c7677a4ef915.png)

ported to my tree( https://github.com/roytam1/rtoss/compare/master...greenpad-aboutdlg ), looks great!
![image](https://user-images.githubusercontent.com/1192577/221750940-663febcc-4137-4222-9b5f-cfc60fa8bf82.png)
![image](https://user-images.githubusercontent.com/1192577/221751036-fbf48f47-5c36-44b8-a44c-a0e0fe880138.png)

**Comment by RamonUnch** [comment]
Nice, Good idea to add OLE build flags, also you know how to write the title in Japanese, Should not the original author's name be also written in Japanese on the Japanese dialog? Also I should probably write the full name *Kazuhiro Inaba* on the English dialog

**Comment by RamonUnch** [comment]
Also for x64 built, I guess we should specify Windows NT 5.1+ because x86_64 started with XP64.

**Comment by roytam1** [comment]
> Should not the original author's name be also written in Japanese on the Japanese dialog?

but he called himself "k.inaba" so I don't want to change it.
Ref: https://www.kmonos.net/lib/suspend.ja.html

**Comment by RamonUnch** [comment]
Then I agree, we must use *k.inaba* then.

**Comment by roytam1** [comment]
> Good idea to add OLE build flag

I'm thinking about adding "running on Windows X.Y.ZZZZ" on 4th line of top textbox.

**Comment by RamonUnch** [comment]
> I'm thinking about adding "running on Windows X.Y.ZZZZ" on 4th line of top textbox.

Would be helpful indeed, I will do that.

**Comment by roytam1** [comment]
> Would be helpful indeed, I will do that.

cool. trying to add back the dot for msvc version.
![image](https://user-images.githubusercontent.com/1192577/221885175-94f1a170-8089-4438-bb43-503a8f2982b2.png)

**Comment by RamonUnch** [comment]
> cool. trying to add back the dot for msvc version.

`_MSVC_VER` info:
https://dev.to/yumetodo/list-of-mscver-and-mscfullver-8nd
Since Visual C++ 4.0 the formula should be `(_MSVC_VER-600)/100 DOT _MSVC_VER%100)

**Comment by roytam1** [comment]
> Since Visual C++ 4.0 the formula should be `(_MSC_VER-600)/100 DOT _MSC_VER%100)`

yeah, force pushed my branch

**Comment by RamonUnch** [comment]
However since Visual studio 2017 it became strange and we are still at 14.XX, even though the commercial number went to 15+

**Comment by DotNetTester** [comment]
> The dialog uses the default dialog font, I can of course increase the font size but keep in mind that the dpi of ~y~ my monitor is set to 96, most people now use 120 or more meaning the font will look much larger. If the DPI setting on your screen is so small that the common dialogs appear too small to your eyes you might also consider increasing the DPI value. I can push up a little the font size but not by much before it looks out of place.
> 

A size of 10 would be bigger and more readable. I personally wouldn't go above a size of 12.

There are people that switch their computers to 96 dpi due to the fact that even some new apps either break or become blurry with high DPI settings. You can lower the resolution on larger displays to make the text bigger at 96 dpi.

**Comment by roytam1** [comment]
synced to my vc4-mips tree and it is working well!
![image](https://user-images.githubusercontent.com/1192577/222178174-5784ee19-741e-4d4e-a2b6-ce4ec472b74b.png)

**Comment by RamonUnch** [comment]
1.17 released

**Comment by roytam1** [comment]
Text boxes may not have gray background in NT 3.51, I added some code to deal with it.
![image](https://github.com/RamonUnch/GreenPad/assets/1192577/601f7c03-ffee-435f-9359-b0589bf28da4)

https://github.com/roytam1/rtoss/commit/704df7dc2bcc998b8f9acd041d926473e0bb2ba2
https://github.com/roytam1/rtoss/commit/d6edc56bf97fe5e80b13c974b9a50b43f410b633
