### ISSUE TITLE
Impossible to select Character Encoding or Line ending with TAB on Open/Save dialogs

### ISSUE THREAD

**Issue by RamonUnch** [RamonUnch/GreenPad#83]
I am unable to select any of the extra controls that are added to the open or the save dialogs without using the mouse. I would like to be able to select with TAB and also select using Alt+C cor *&Character encoding* and Alt+L for *&Line ending*

@roytam1 maybe you have some ideas?

Actually I can get it to work adding the `EXSTYLE WS_EX_CONTROLPARENT` on the dialog resource but I am unsure this is what we are supposed to do, because it is not present on the notepad.exe from WinXP.

Also I am trying to figure out what the first line of the IDD_SAVEFILEHOOK/IDD_OPENFILEHOOK is all about:
```c
    LTEXT           "",1119,0,0,187,13,SS_SUNKEN | NOT WS_VISIBLE | NOT WS_GROUP
```

**Comment by roytam1** [comment]
> Also I am trying to figure out what the first line of the IDD_SAVEFILEHOOK/IDD_OPENFILEHOOK is all about:
> 
> ```c
>     LTEXT           "",1119,0,0,187,13,SS_SUNKEN | NOT WS_VISIBLE | NOT WS_GROUP
> ```

maybe some kind of compatibility? if you change this, you may need to test with Chicago 4.00.180, NT 3.5x with NewShell, NT4, Win95 with Desktop update, and more.

**Comment by RamonUnch** [comment]
`DS_CONTROL` seems to do the trick for me, it was added with NT3.51/Win95 from what I understand to allow nested dialogs.
It should be fine to use because on older Windows we use the old style dialog.

**Comment by roytam1** [comment]
> I will have a go at installing NewShell on NT3.51, but it really seems weird to me.

NewShell for NT 3.50.854 is something weirder. glad that it doesn't come with new comdlg32.

**Comment by RamonUnch** [comment]
New shell beta 1 (May 26 1995) on NT3.51sp5: No new style dialog available!
New Shell beta 2 (August 9 1995) on NT3.51sp5: Works fine even without the funny line. TAB does not work though.
